services:
  web:
    container_name: my-nginx
    image: nginx:1.20.2-alpine 
    ports:
      - 8080:80
    volumes:
      - ./static:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  node-socket:
    container_name: my-node-socket
    build: .
    ports:
      - 6152:6152


